/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, URISyntaxException {
            App app = new App();
            Class class1 = app.getClass();
            URL url = class1.getResource("../../sample.bmp/");
        File file = new File(url.toURI());
        BufferedImage image = ImageIO.read(file);
        BitMap x = new  BitMap("immm" , "./app/src/main/resources" , url.getPath());

        x.cyanBorder();
    }
}
