/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) throws IOException{
        BitMap withBorder = new  BitMap("border_Image", "./app/src/main/resources" , "./app/src/main/resources/sample.bmp");
        BitMap noBlue = new  BitMap("filtered_Image", "./app/src/main/resources" , "./app/src/main/resources/sample.bmp");
        BitMap noGreen = new  BitMap("filtered_Imageg", "./app/src/main/resources" , "./app/src/main/resources/sample.bmp");
        withBorder.cyanBorder();                noBlue.filterBlue();
        noGreen.filterGreen();

        // mohammad jaradat
        BitMap borderRed = new BitMap("OrangeBorder", "./src", "./app/src/main/resources/sample.bmp");
        BitMap twoColorBorder = new BitMap("twoColorBorder", "./src", "./app/src/main/resources/sample.bmp");
        BitMap magentaAndCyanBorder = new BitMap("magentaAndCyanBorder", "./src", "./app/src/main/resources/sample.bmp");

        borderRed.OrangeBorder();        twoColorBorder.twoColorBorder();
        magentaAndCyanBorder.magentaAndCyanBorder();


//        For Command line run
        String transName = args[0] , outPut = args[1] , inPut = args[2];
        try{
            if(transName.equals("cyanBorder")) {
                BitMap x = new  BitMap(transName, outPut , inPut);
                x.cyanBorder();
            }

            else if(transName.equals("filter")) {
                BitMap x = new  BitMap(transName, outPut , inPut);
                x.filterBlue();
            }

            if(transName.equals("OrangeBorder")) {
                BitMap x = new  BitMap(transName, outPut , inPut);
                x.OrangeBorder();
            }
            if (transName.equals("twoColorBorder")){
                BitMap x = new  BitMap(transName, outPut , inPut);
                x.twoColorBorder();
            }
            if (transName.equals("magentaAndCyanBorder")){
                BitMap x = new  BitMap(transName, outPut , inPut);
                x.magentaAndCyanBorder();
            }
        }

        catch (IOException e) {
            System.out.println("An error occured with the path");
        }
    }

//    "./app/src/main/resources"
//    "./app/src/main/resources/sample.bmp"
}
